language: ruby
rvm:
  - 2.1.3

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database ruhr_top_card_locator_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - npm install

script:
  - bundle exec rspec spec
  - bundle exec rake karma:run

cache:
  bundler: true
  directories:
    - node_modules