development:
  adapter: postgresql
  encoding: unicode
  database: ruhrtopcard_locator_development
  username: dmasur
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ruhrtopcard_locator_test
  username: dmasur
  host: localhost
  password: