# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1d400c08ffcb1bd8d8282c9e28226809762fa885422857f935a6694748a6e5b61bf59818dd91e9bfb9d653a42b26120834ee00ee53378b9a9476756d7a243d4

test:
  secret_key_base: cf64b37c27640c0b4db941fcd3fa8ae8933aede44761a6114f43ae75990c851df0920db4af700d0c3e35741d7183a0a5dec359a77e1bbb1d331c520324413f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
